name: chat_app
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.9.0

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  flutter_screenutil: ^5.9.3
  get_it: ^8.2.0
  supabase_flutter: ^2.10.0
  bloc: ^9.0.0
  flutter_bloc:
  flutter_contacts: ^1.1.9+2
  equatable: ^2.0.7
  animated_text_kit: ^4.2.3
  intl: ^0.20.2
  flutter_launcher_icons: ^0.14.4
  visibility_detector: ^0.4.0+2
  flutter_svg: ^2.2.1
  app_links:
  record: ^6.1.1             # للتسجيل
  path_provider:    # لإيجاد temporary dir
  uuid:               # لتوليد أسماء ملفات فريدة
  audioplayers: 
  permission_handler: ^12.0.1
  lottie: ^3.3.1
  pin_code_fields: ^8.0.1
  image_picker: ^1.2.0
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true

  # assets inside the app
  assets:
    - assets/image/
    - assets/svg/
    - assets/lottie/


flutter_icons:
  android: true
  ios: true
  image_path: "assets/image/App Icone.png" 
